blank_issues_enabled: true
contact_links:
  - name: Code of Conduct
    url: https://github.com/miloszkolber/mewa_code/blob/main/docs/code-of-conduct.md
    about: Please follow the project's Code of Conduct when participating in this project.
